name: template
version: 1.0.0
description: This template is meant to allow developers to quickly get started
  with Appwrite's Cloud Functions. Just follow along

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dart_appwrite: ^0.1.0
