language: php

php:
  - '7.4'

addons:
  hosts:
    - appwrite.test

notifications:
  email:
  - team@appwrite.io
  
services:
- docker

install:
# - >
#     echo "80\n443\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" | docker run --rm \
#         --volume /var/run/docker.sock:/var/run/docker.sock \
#         --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
#         --entrypoint="install" \
#         appwrite/appwrite:dev --version=dev
# - sleep 90
- docker-compose up -d
- sleep 10
- docker-compose logs mariadb
- docker-compose exec mariadb ls /docker-entrypoint-initdb.d
- docker-compose exec mariadb cat /docker-entrypoint-initdb.d/all.sql
- docker-compose exec mariadb mysqldump --user=root --password=rootsecretpassword appwrite

script:
- docker ps
# - cd appwrite
# - docker-compose exec appwrite doctor
# - docker-compose logs mariadb
# - docker-compose exec mariadb mysqldump --user root --password=rootsecretpassword appwrite
# - docker-compose exec mariadb ls /docker-entrypoint-initdb.d
# - docker-compose exec mariadb cat /docker-entrypoint-initdb.d/all.sql
# - cat .env
# - cat docker-compose.yml
# - docker-compose restart mariadb
# - sleep 10
# - docker-compose exec appwrite doctor
# - composer update --ignore-platform-reqs --optimize-autoloader --no-plugins --no-scripts --prefer-dist
# - vendor/bin/phpunit --configuration ./phpunit.xml ./tests